name: Build Decimbot2 Docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag decimbot2:1.0.${{github.run_number}}
      
    - uses: azure/docker-login@v1
    - name: Login to ACR
      with:
        login-server: ${{ secrets.ACR_ENDPOINT }}
        username: ${{ secrets.ACR_LOGINNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
      
    - name: Publish image to ACR
      run: docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/sampleapp:${{ github.sha }}


